**Data Loading, Storage,**

In [ ]:
import numpy as np
import pandas as pd

**Reading and Writing Data in Text Format**

In [ ]:
df1 = pd.read_csv('/content/sample_data/ex1.csv')
df1

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [ ]:
df1=pd.read_table('/content/sample_data/ex1.csv', sep=',')
df1

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [ ]:
df2=pd.read_csv('/content/sample_data/ex2.csv', header=None, names=['a', 'b', 'c', 'd', 'message'])
df2

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [ ]:
!cat /content/sample_data/csv_mindex.csv

key1,key2,value1,value2
one,a,1,2
one,b,3,4
one,c,5,6
one,d,7,8
two,a,9,10
two,b,11,12
two,c,13,14
two,d,15,16

In [ ]:
df3=pd.read_csv('/content/sample_data/csv_mindex.csv', index_col=['key1', 'key2'])
df3

           value1  value2
key1 key2
one  a          1       2
     b          3       4
     c          5       6
     d          7       8
two  a          9      10
     b         11      12
     c         13      14
     d         15      16

In [ ]:
list(open('/content/sample_data/ex3.txt'))

['            A         B         C\n',
 'aaa -0.264438 -1.026059 -0.619500\n',
 'bbb  0.927272  0.302904 -0.032399\n',
 'ccc -0.264273 -0.386314 -0.217601\n',
 'ddd -0.871858 -0.348382  1.100491']

In [ ]:
df3 = pd.read_table('/content/sample_data/ex3.txt', sep='\s+')
df3

            A         B         C
aaa -0.264438 -1.026059 -0.619500
bbb  0.927272  0.302904 -0.032399
ccc -0.264273 -0.386314 -0.217601
ddd -0.871858 -0.348382  1.100491

In [ ]:
!cat /content/sample_data/ex4.csv

# hey!
a,b,c,d,message
# just wanted to make things more difficult for you
# who reads CSV files with computers, anyway?
1,2,3,4,hello
5,6,7,8,world
9,10,11,12,foo

In [ ]:
df4=pd.read_csv('/content/sample_data/ex4.csv', skiprows=[0, 2, 3])
df4

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [ ]:
df5 = pd.read_csv('/content/sample_data/ex5.csv')
df5
pd.isnull(df5)

   something      a      b      c      d  message
0      False  False  False  False  False     True
1      False  False  False   True  False    False
2      False  False  False  False  False    False

In [ ]:
df5 = pd.read_csv('/content/sample_data/ex5.csv', na_values=['NULL'])
df5

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [ ]:

sentinels = {'message': ['foo', 'NA'], 'something': ['two']}
pd.read_csv('/content/sample_data/ex5.csv', na_values=sentinels)

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       NaN  5   6   NaN   8   world
2     three  9  10  11.0  12     NaN

In [ ]:
sentinels = {'a': ['5'], 'b': ['2'], 'something': ['three']}
pd.read_csv('/content/sample_data/ex5.csv', na_values=sentinels)

  something    a     b     c   d message
0       one  1.0   NaN   3.0   4     NaN
1       two  NaN   6.0   NaN   8   world
2       NaN  9.0  10.0  11.0  12     foo

**Reading Text Files in Pieces**

In [ ]:
pd.options.display.max_rows = 10

In [ ]:
df6=pd.read_csv('/content/sample_data/ex6.csv')
df6

           one       two     three      four key
0     0.467976 -0.038649 -0.295344 -1.824726   L
1    -0.358893  1.404453  0.704965 -0.200638   B
2    -0.501840  0.659254 -0.421691 -0.057688   G
3     0.204886  1.074134  1.388361 -0.982404   R
4     0.354628 -0.133116  0.283763 -0.837063   Q
...        ...       ...       ...       ...  ..
9995  2.311896 -0.417070 -1.409599 -0.515821   L
9996 -0.479893 -0.650419  0.745152 -0.646038   E
9997  0.523331  0.787112  0.486066  1.093156   K
9998 -0.362559  0.598894 -1.843201  0.887292   G
9999 -0.096376 -1.012999 -0.657431 -0.573315   0

[10000 rows x 5 columns]

In [ ]:
df6=pd.read_csv('/content/sample_data/ex6.csv',nrows=5)
df6

        one       two     three      four key
0  0.467976 -0.038649 -0.295344 -1.824726   L
1 -0.358893  1.404453  0.704965 -0.200638   B
2 -0.501840  0.659254 -0.421691 -0.057688   G
3  0.204886  1.074134  1.388361 -0.982404   R
4  0.354628 -0.133116  0.283763 -0.837063   Q

In [ ]:
df6=pd.read_csv('/content/sample_data/ex6.csv', chunksize=1000)
df6

In [ ]:
df6=pd.read_csv('/content/sample_data/ex6.csv', chunksize=1000)
tot = pd.Series([])
for piece in df6:
    tot = tot.add(piece['key'].value_counts(), fill_value=0)

tot = tot.sort_values(ascending=False)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.

In [ ]:

tot[:10]

E    368.0
X    364.0
L    346.0
O    343.0
Q    340.0
M    338.0
J    337.0
F    335.0
K    334.0
H    330.0
dtype: float64

**Writing Data to Text Format**

In [ ]:
data = pd.read_csv('/content/sample_data/ex5.csv')
data

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [ ]:
data.to_csv('/content/sample_data/out.csv')
!cat /content/sample_data/out.csv

,something,a,b,c,d,message
0,one,1,2,3.0,4,
1,two,5,6,,8,world
2,three,9,10,11.0,12,foo

In [ ]:
import sys
data.to_csv(sys.stdout, sep='|')

|something|a|b|c|d|message
0|one|1|2|3.0|4|
1|two|5|6||8|world
2|three|9|10|11.0|12|foo

In [ ]:
data.to_csv(sys.stdout, na_rep='NULL')

,something,a,b,c,d,message
0,one,1,2,3.0,4,NULL
1,two,5,6,NULL,8,world
2,three,9,10,11.0,12,foo

In [ ]:
data.to_csv(sys.stdout, index=False, header=False)

one,1,2,3.0,4,
two,5,6,,8,world
three,9,10,11.0,12,foo

In [ ]:
data.to_csv(sys.stdout, index=False, columns=['a', 'b', 'c'])

a,b,c
1,2,3.0
5,6,
9,10,11.0

In [ ]:
dates = pd.date_range('1/1/2000', periods=7)
ts = pd.Series(np.arange(7), index=dates)
ts.to_csv('/content/sample_data/tseries.csv')
!cat /content/sample_data/tseries.csv

,0
2000-01-01,0
2000-01-02,1
2000-01-03,2
2000-01-04,3
2000-01-05,4
2000-01-06,5
2000-01-07,6

**Working with Delimited Formats**

In [ ]:
!cat /content/sample_data/ex7.csv

"a","b","c"
"1","2","3"
"1","2","3"

In [ ]:
import csv
f = open('/content/sample_data/ex7.csv')

reader = csv.reader(f)

In [ ]:
for line in reader:
    print(line)

['a', 'b', 'c']
['1', '2', '3']
['1', '2', '3']

In [ ]:
with open('/content/sample_data/ex7.csv') as f:
    lines = list(csv.reader(f))

In [ ]:
header, values = lines[0], lines[1:]

In [ ]:
data_dict = {h: v for h, v in zip(header, zip(*values))}
data_dict

{'a': ('1', '1'), 'b': ('2', '2'), 'c': ('3', '3')}

**JSON Data**

In [ ]:
obj = """
{"name": "Wes",
 "places_lived": ["United States", "Spain", "Germany"],
 "pet": null,
 "siblings": [{"name": "Scott", "age": 30, "pets": ["Zeus", "Zuko"]},
              {"name": "Katie", "age": 38,
               "pets": ["Sixes", "Stache", "Cisco"]}]
}
"""

In [ ]:
import json
result = json.loads(obj)
result

{'name': 'Wes',
 'pet': None,
 'places_lived': ['United States', 'Spain', 'Germany'],
 'siblings': [{'age': 30, 'name': 'Scott', 'pets': ['Zeus', 'Zuko']},
  {'age': 38, 'name': 'Katie', 'pets': ['Sixes', 'Stache', 'Cisco']}]}

In [ ]:
asjson = json.dumps(result)

In [ ]:
siblings = pd.DataFrame(result['siblings'], columns=['name', 'age'])
siblings

    name  age
0  Scott   30
1  Katie   38

In [ ]:
!cat /content/sample_data/example.json

[{"a": 1, "b": 2, "c": 3},
 {"a": 4, "b": 5, "c": 6},
 {"a": 7, "b": 8, "c": 9}]

In [ ]:
data = pd.read_json('/content/sample_data/example.json')
data

   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

In [ ]:
print(data.to_json())
print(data.to_json(orient='records'))

{"a":{"0":1,"1":4,"2":7},"b":{"0":2,"1":5,"2":8},"c":{"0":3,"1":6,"2":9}}
[{"a":1,"b":2,"c":3},{"a":4,"b":5,"c":6},{"a":7,"b":8,"c":9}]

**XML and HTML: Web Scraping**

In [ ]:
tables = pd.read_html('/content/sample_data/fdic_failed_bank_list.html')
len(tables)
failures = tables[0]
failures.head()

                      Bank Name  ...       Updated Date
0                   Allied Bank  ...  November 17, 2016
1  The Woodbury Banking Company  ...  November 17, 2016
2        First CornerStone Bank  ...  September 6, 2016
3            Trust Company Bank  ...  September 6, 2016
4    North Milwaukee State Bank  ...      June 16, 2016

[5 rows x 7 columns]

In [ ]:
close_timestamps = pd.to_datetime(failures['Closing Date'])
close_timestamps.dt.year.value_counts()

2010    157
2009    140
2011     92
2012     51
2008     25
       ...
2004      4
2001      4
2007      3
2003      3
2000      2
Name: Closing Date, Length: 15, dtype: int64

**Parsing XML with lxml.objectify**

In [ ]:
from lxml import objectify

path = '/content/sample_data/Performance_MNR.xml'
parsed = objectify.parse(open(path))
root = parsed.getroot()

In [ ]:
data = []

skip_fields = ['PARENT_SEQ', 'INDICATOR_SEQ',
               'DESIRED_CHANGE', 'DECIMAL_PLACES']

for elt in root.INDICATOR:
    el_data = {}
    for child in elt.getchildren():
        if child.tag in skip_fields:
            continue
        el_data[child.tag] = child.pyval
    data.append(el_data)

In [ ]:
perf = pd.DataFrame(data)
perf.head()

            AGENCY_NAME  ... MONTHLY_ACTUAL
0  Metro-North Railroad  ...           96.9
1  Metro-North Railroad  ...             95
2  Metro-North Railroad  ...           96.9
3  Metro-North Railroad  ...           98.3
4  Metro-North Railroad  ...           95.8

[5 rows x 12 columns]

In [ ]:
from io import StringIO
tag = '<a href="http://www.google.com">Google</a>'
root = objectify.parse(StringIO(tag)).getroot()

In [ ]:
root
root.get('href')
root.text

'Google'

**Binary Data Formats**

In [ ]:
frame = pd.read_csv('/content/sample_data/ex1.csv')
frame
frame.to_pickle('/content/sample_data/frame_pickle')

In [ ]:
pd.read_pickle('/content/sample_data/frame_pickle')

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [ ]:
!rm /content/sample_data/frame_pickle

**Using HDF5 Format**

In [ ]:
frame = pd.DataFrame({'a': np.random.randn(100)})
store = pd.HDFStore('mydata.h5')
store['obj1'] = frame
store['obj1_col'] = frame['a']
store

<class 'pandas.io.pytables.HDFStore'>
File path: mydata.h5

In [ ]:
store['obj1']

           a
0   1.102883
1   0.087104
2   1.588765
3   0.701853
4   0.190330
..       ...
95  1.475088
96  0.705207
97 -0.035246
98  0.856961
99 -2.294821

[100 rows x 1 columns]

In [ ]:
store.put('obj2', frame, format='table')
store.select('obj2', where=['index >= 10 and index <= 15'])
store.close()

In [ ]:
frame.to_hdf('mydata.h5', 'obj3', format='table')
pd.read_hdf('mydata.h5', 'obj3', where=['index < 5'])

          a
0  1.102883
1  0.087104
2  1.588765
3  0.701853
4  0.190330

In [ ]:
!rm /content/mydata.h5

**Reading Microsoft Excel Files**

In [ ]:
xlsx = pd.ExcelFile('/content/sample_data/ex1.xlsx')

In [ ]:
pd.read_excel(xlsx, 'Sheet1')

   Unnamed: 0  a   b   c   d message
0           0  1   2   3   4   hello
1           1  5   6   7   8   world
2           2  9  10  11  12     foo

In [ ]:
frame = pd.read_excel('/content/sample_data/ex1.xlsx', 'Sheet1')
frame

   Unnamed: 0  a   b   c   d message
0           0  1   2   3   4   hello
1           1  5   6   7   8   world
2           2  9  10  11  12     foo

In [ ]:
writer = pd.ExcelWriter('/content/sample_data/ex2.xlsx')
frame.to_excel(writer, 'Sheet1')
writer.save()

In [ ]:
frame.to_excel('/content/sample_data/ex2.xlsx')

In [ ]:
!rm /content/sample_data/ex2.xlsx

**Interacting with Web APIs**

In [ ]:
import requests
url = 'https://api.github.com/repos/pandas-dev/pandas/issues'
resp = requests.get(url)
resp

In [ ]:
data = resp.json()
data[0]['title']

'REF: reindex_indexer use np.void to avoid JoinUnit'

In [ ]:
issues = pd.DataFrame(data, columns=['number', 'title',
                                     'labels', 'state'])
issues

    number  ... state
0    43376  ...  open
1    43375  ...  open
2    43374  ...  open
3    43373  ...  open
4    43372  ...  open
..     ...  ...   ...
25   43337  ...  open
26   43334  ...  open
27   43330  ...  open
28   43329  ...  open
29   43328  ...  open

[30 rows x 4 columns]

**Interacting with Databases**

In [ ]:
import sqlite3
query = """
CREATE TABLE test
(a VARCHAR(20), b VARCHAR(20),
 c REAL,        d INTEGER
);"""
con = sqlite3.connect('mydata.sqlite')
con.execute(query)
con.commit()

In [ ]:
data = [('Atlanta', 'Georgia', 1.25, 6),
        ('Tallahassee', 'Florida', 2.6, 3),
        ('Sacramento', 'California', 1.7, 5)]
stmt = "INSERT INTO test VALUES(?, ?, ?, ?)"
con.executemany(stmt, data)
con.commit()

In [ ]:
cursor = con.execute('select * from test')
rows = cursor.fetchall()
rows

[('Atlanta', 'Georgia', 1.25, 6),
 ('Tallahassee', 'Florida', 2.6, 3),
 ('Sacramento', 'California', 1.7, 5)]

In [ ]:
cursor.description
pd.DataFrame(rows, columns=[x[0] for x in cursor.description])

             a           b     c  d
0      Atlanta     Georgia  1.25  6
1  Tallahassee     Florida  2.60  3
2   Sacramento  California  1.70  5

In [ ]:
import sqlalchemy as sqla
db = sqla.create_engine('sqlite:///mydata.sqlite')
pd.read_sql('select * from test', db)

             a           b     c  d
0      Atlanta     Georgia  1.25  6
1  Tallahassee     Florida  2.60  3
2   Sacramento  California  1.70  5

In [ ]:
!rm mydata.sqlite